#!/usr/bin/env python3
"""Asset recon: search Sketchfab for downloadable CC0 / CC-BY snowblower models.

Writes docs/asset-recon/blowers.md as a table (name, URL, license, triangles,
PBR textures, uploader, fit score). Standard library only.

    python3 scripts/sketchfab-search.py [--out PATH] [--pages N]

The search API is public; no token needed. Set SKETCHFAB_API_TOKEN to send one
anyway (higher rate limits).
"""
import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.sketchfab.com/v3/search"
QUERIES = [
    "snowblower",
    "snow blower",
    "snow thrower",
    "two stage snowblower",
    "tracked snowblower",
    "three stage snowblower",
]
ALLOWED_LICENSES = {"cc0": "CC0", "by": "CC-BY"}
PAGE_SIZE = 24
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(ROOT, "docs", "asset-recon", "blowers.md")


def fetch(url):
    headers = {"User-Agent": "SnowblowerSim-asset-recon/1.0"}
    token = os.environ.get("SKETCHFAB_API_TOKEN")
    if token:
        headers["Authorization"] = "Token " + token
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def search(query, pages, pbr_only=False):
    params = {"type": "models", "q": query, "downloadable": "true", "count": PAGE_SIZE}
    if pbr_only:
        params["pbr_type"] = "true"
    url = API + "?" + urllib.parse.urlencode(params)
    results = []
    for _ in range(pages):
        data = fetch(url)
        results.extend(data.get("results", []))
        url = data.get("next")
        if not url:
            break
        time.sleep(0.5)  # be polite
    return results


def license_of(model):
    lic = model.get("license") or {}
    slug = (lic.get("slug") or "").lower()
    return ALLOWED_LICENSES.get(slug)


def max_texture_res(model):
    archives = model.get("archives") or {}
    res = [a.get("textureMaxResolution") for a in archives.values() if isinstance(a, dict)]
    res = [r for r in res if r]
    return max(res) if res else None


def collect(pages):
    models = {}
    for query in QUERIES:
        pbr_uids = {m["uid"] for m in search(query, pages, pbr_only=True)}
        for m in search(query, pages):
            lic = license_of(m)
            if not lic or not m.get("isDownloadable", True):
                continue
            entry = models.setdefault(m["uid"], {
                "name": m.get("name", "?"),
                "url": m.get("viewerUrl") or "https://sketchfab.com/3d-models/" + m["uid"],
                "license": lic,
                "triangles": m.get("faceCount"),
                "pbr": False,
                "tex": max_texture_res(m),
                "uploader": (m.get("user") or {}).get("username", "?"),
                "queries": [],
            })
            entry["pbr"] = entry["pbr"] or m["uid"] in pbr_uids
            entry["queries"].append(query)
    return sorted(models.values(), key=lambda e: (e["license"] != "CC0", e["name"].lower()))


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(models):
    lines = [
        "# Blower models — Sketchfab recon",
        "",
        "Generated by `scripts/sketchfab-search.py` on %s." % time.strftime("%Y-%m-%d"),
        "Queries: %s. Filters: downloadable, license CC0 or CC-BY." % ", ".join('"%s"' % q for q in QUERIES),
        "",
        "Fit score (1–5) is filled in by hand: photoreal fit, scale accuracy, topology, textures.",
        "",
        "| Name | URL | License | Triangles | PBR textures | Uploader | Fit score |",
        "|---|---|---|---:|---|---|---|",
    ]
    for m in models:
        tris = "{:,}".format(m["triangles"]) if m["triangles"] else "?"
        pbr = "Yes" if m["pbr"] else "No"
        if m["tex"]:
            pbr += " (max %spx)" % m["tex"]
        lines.append("| %s | %s | %s | %s | %s | %s |  |" % (
            cell(m["name"]), m["url"], m["license"], tris, pbr, cell(m["uploader"])))
    if not models:
        lines.append("| _no matching models_ |  |  |  |  |  |  |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--pages", type=int, default=3, help="result pages per query (24 each)")
    args = ap.parse_args()

    try:
        models = collect(args.pages)
    except (urllib.error.URLError, OSError) as e:
        print("sketchfab-search: API unreachable (%s). Run this on a machine with access to "
              "api.sketchfab.com." % e, file=sys.stderr)
        return 2

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render(models))
    print("sketchfab-search: %d models -> %s" % (len(models), args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
